Como importar um arquivo

In [ ]:
from google.colab import files
upload = files.upload()

## Introdução

# Variáveis e Objetos

In [ ]:
# Variavel do tipo inteiro
x = 1;
# Variavel do tipo float
y = 3.13;
# Variavel do tipo string
z = "Python";
z = 'Python';
# Variavel do tipo lógica
w = True;
w = False;
#Exibir valores no console
print("Este texto é exibido no console")
print(x)

Este texto é exibido no console
1


In [ ]:
#Verificar tipo
type(x)
type(z)

str

In [ ]:
#Entrada de valores
x = input("Informe um valor")

In [ ]:
# Conversão de valores
a = int(y)
b = str(z)
t = float(3)

print(a, b, t)

3 Python 3.0


In [ ]:
#Operadores lógicos
and
or
not

# Estrutura de repetição

In [ ]:
count = 1
while count <=5:
  print(count)
  count += 1

In [ ]:
for n in range(0, 10):
  print(n)

In [ ]:
# range(inicio, parada, incremento/decremento)
for n in range(0, 10, 1):
  #cancela o laço
  break
  #reinicia o laço
  continue
  print(n)

# Listas

In [ ]:
lst = [1, 2, 3, 4, 5]
lst2 = [1, 2, 3, "4", True]
lst3 = [12, [1,2,3,4,5], "a"]
lst4 = list(range(0,10))

len(lst) #numero de elementos em uma lista

# Dicionarios, Sets e Tuplas

In [ ]:
#Dicionario
#conjunto de chave / valor associado
#Declarados por chaves e separados por dois pontos
Precos = {'lapis': 5.5, 'borracha': 7.0, 'caneta':6.5}
#lapis -> chave / 5.5 -> valor

#Sets
#conjuntos não ordenados e não repetidos de elementos
animais = {'gato', 'cachorro'}

#Tuplas
#Tuplas são listas que não podem ser alteradas
tp1 = (1,2,3,4,5,6)

In [ ]:
Notas = {'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
print(Notas)

In [ ]:
print(Notas['João'])

In [ ]:
Notas.keys()

In [ ]:
Notas.values()

In [ ]:
print('João' in Notas)
print('Fernando' in Notas)

In [ ]:
del Notas['João']
print(Notas)

In [ ]:
Notas['Ana'] = 9
print(Notas)

In [ ]:
Notas.get('Geraldo', 'Não encontrado!')

In [ ]:
bigdata = {'Spark', 'Hive', 'Sqoop'}
print(bigdata)

In [ ]:
print('Spark' in bigdata)

In [ ]:
bigdata.add('Hadoop')
bigdata

In [ ]:
print(len(bigdata))

In [ ]:
bigdata.add('Spark')
bigdata
#Elemento repetido não são adicionados

NameError: ignored

In [ ]:
tupla = (1,2,3,4,5,6,7)
tupla

In [ ]:
tupla[4]

In [ ]:
dic2 = {(0,1):0, (1,2): 1, (2,3): 2, (3,4): 3, (4,5):4, (5,6): 5, (6,7):6, (7,8): 7, (8,9): 8, (9,10):9}
dic2

In [ ]:
print(type(Notas))
print(type(bigdata))
print(type(tupla))

# Numpy

In [ ]:
import numpy as np

In [ ]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [ ]:
#criar o array com um tipo específico
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#mudar o tipo do array
# Podemos transformar tipos de dados de arays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.9999999])
print(mtnew)
#quando transformamos de float para int os valores são rtuncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4        3.6       -5.1        9.42       4.9999999]
[ 1  3 -5  9  4]


In [ ]:
#podemos fazer o inverso também
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
#mais de uma dimensão
#cria matriz bidimensional
mt7 = np.array([[7,2,23],[12,8,6],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12  8  6]
 [ 5 34 23]]


In [ ]:
#criar arrays vazios tipificados
#empty significa não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype=int)
print(vazio)
print('------')
#cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print('------')
#com valores igual a um
um = np.ones([5,7])
print(um)
print('------')
#cira uma matriz quadrada com diagonal principal com valores 1 e os outros zero
diagonal = np.eye(5)
print(diagonal)

[[101567931005065               0]
 [   416611827815    137438953580]
 [   433791697011    459561500773]]
------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print('------')
#valores aleatórios distr, normal contendo negativos
ale2 = np.random.randn((5))
print(ale2)
print('------')
#valores aleatórios 3 x 4
ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.82448765 0.20169607 0.54606583 0.80597375 0.33878615]
------
[-1.25467332  0.05958268 -0.66509402  0.55385525 -0.34081574]
------
[[0.67515926 2.7506573  1.09451628 4.616745  ]
 [7.60645526 5.67509651 7.0362064  5.01000992]
 [3.32170483 7.87869776 8.20455795 4.33017422]]


In [ ]:
#outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [ ]:
#unique remove repetições
j = np.array([11,12,13,14,15,16,17,12,13,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#funções específicas
# cria a matriz dimensional k
k = np.array([[7,2,23],[12,8,6],[5,34,23]])
#mostra a matriz k
print(k)
# mostra um elemento especifico da matriz k
print(k[0][1])
# mostra o tamanho das dimensões da matriz k
print(k.shape)

[[ 7  2 23]
 [12  8  6]
 [ 5 34 23]]
2
(3, 3)


In [ ]:
#Funções matemáticas
# mostra o maior valor da matriz k
print(k.max())
#mostra o menor valor da matriz k
print(k.min())
#mostra a soma dos valores da matriz k
print(k.sum())
#mostra o valor da média dos valores da matriz k
print(k.mean())
# mostra o valor do desvio padrao (standard derivation) dos valores da matriz k
print(k.std())

34
2
120
13.333333333333334
10.198039027185569


In [ ]:
#Funções universais, aplicadas a todos os elementos
#Mostra o valor da raiz quadrada de todos os elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))
#Mostra o valor exponencial de todos os elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [ ]:
#extração de elementos
m = np.array([1,2,3,4,5,6])
#Mostra o elemento da posição 2
print(m[1])
print('-------')
#mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print('-------')
#Mostra o array criado a partir da 2a posição até todo o restante do array
print(m[1:])
print('-------')
#mostra o array criado a partir da antepenultima posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [ ]:
#extração de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)
print('-------')
#primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)
print('-------')
#segunda linha
l_linha_2 = l[1, :]
print(l_linha_2)
print('-------')
#todas as linhas, primeira coluna
l_coluna_1 = l[: ,0]
print(l_coluna_1)
print('-------')
#todas as linhas, segunda coluna
l_coluna_2 = l[: ,1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[4 6 7]
-------
[5 1 4]


In [ ]:
#adição e multiplicação de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])

res1 = n+o
print(res1)
print('-------')
res2=n*o
print(res2)
print('-------')
p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(p+q)


[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [ ]:
#transposição, rearranja um conjunto de 15 elementos de 0 a 14
#em 3 linhas e 5 colunas.
f = np.arange(15).reshape((3,5))
#mostra a matriz transposta entre linha e coluna
print(f)
print("-------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
# outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))
print(r)
print("------")
#rearranja um conjunto de 15 elementos
# mostra a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [ ]:
#expressões lógicas
#usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)
#riando mari com valores booleanos baseado no array v
x = (v>0)
print(x)
#criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.45653519  1.26067945  0.17366788 -0.5708103 ]
 [-0.50052592  0.83795294  0.89275558  0.25145112]
 [ 0.48428263 -0.95746478  0.21048692 -1.61089935]
 [-0.61404608 -0.78060657 -0.34474434 -0.11888411]]
[[ True  True  True False]
 [False  True  True  True]
 [ True False  True False]
 [False False False False]]
[[ 1  1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1 -1]]


# Pandas

In [4]:
import pandas as pd

In [5]:
#carrega arquivos para dataframe Pandas
dados = pd.read_csv("Credit.csv")
#formato
dados.shape

(1000, 21)

In [6]:
#resumo estatístico de colunas numéricas
dados.describe()

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

In [7]:
#primeiros registros
dados.head()

checking_status  duration                    credit_history  \
0              <0         6  'critical/other existing credit'   
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   
4              <0        24              'delayed previously'   

               purpose  credit_amount      savings_status employment  \
0             radio/tv           1169  'no known savings'        >=7   
1             radio/tv           5951                <100     1<=X<4   
2            education           2096                <100     4<=X<7   
3  furniture/equipment           7882                <100     4<=X<7   
4            'new car'           4870                <100     1<=X<4   

   installment_commitment       personal_status other_parties  ...  \
0                       4         'male single'          none  ...   
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   
4                       3         'male single'          none  ...   

    property_magnitude age  other_payment_plans     housing existing_credits  \
0        'real estate'  67                 none         own                2   
1        'real estate'  22                 none         own                1   
2        'real estate'  49                 none         own                1   
3     'life insurance'  45                 none  'for free'                1   
4  'no known property'  53                 none  'for free'                2   

                    job num_dependents  own_telephone foreign_worker class  
0               skilled              1            yes            yes  good  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  
4               skilled              2           none            yes   bad  

[5 rows x 21 columns]

In [8]:
#ultimos registros, com parametros
dados.tail(2)

checking_status  duration                    credit_history     purpose  \
998              <0        45                   'existing paid'    radio/tv   
999        0<=X<200        45  'critical/other existing credit'  'used car'   

     credit_amount savings_status  employment  installment_commitment  \
998           1845           <100      1<=X<4                       4   
999           4576     100<=X<500  unemployed                       3   

    personal_status other_parties  ...   property_magnitude age  \
998   'male single'          none  ...  'no known property'  23   
999   'male single'          none  ...                  car  27   

     other_payment_plans     housing existing_credits      job num_dependents  \
998                 none  'for free'                1  skilled              1   
999                 none         own                1  skilled              1   

     own_telephone foreign_worker class  
998            yes            yes   bad  
999           none            yes  good  

[2 rows x 21 columns]

In [9]:
#filtrar por nome da coluna
dados[["duration"]]

duration
0           6
1          48
2          12
3          42
4          24
..        ...
995        12
996        30
997        12
998        45
999        45

[1000 rows x 1 columns]

In [10]:
#filtrar linhas por indice
dados.loc[1:3]

checking_status  duration                    credit_history  \
1        0<=X<200        48                   'existing paid'   
2   'no checking'        12  'critical/other existing credit'   
3              <0        42                   'existing paid'   

               purpose  credit_amount savings_status employment  \
1             radio/tv           5951           <100     1<=X<4   
2            education           2096           <100     4<=X<7   
3  furniture/equipment           7882           <100     4<=X<7   

   installment_commitment       personal_status other_parties  ...  \
1                       2  'female div/dep/mar'          none  ...   
2                       2         'male single'          none  ...   
3                       2         'male single'     guarantor  ...   

   property_magnitude age  other_payment_plans     housing existing_credits  \
1       'real estate'  22                 none         own                1   
2       'real estate'  49                 none         own                1   
3    'life insurance'  45                 none  'for free'                1   

                    job num_dependents  own_telephone foreign_worker class  
1               skilled              1           none            yes   bad  
2  'unskilled resident'              2           none            yes  good  
3               skilled              2           none            yes  good  

[3 rows x 21 columns]

In [11]:
#linhas 1 e 3
dados.loc[[1,3]]

checking_status  duration   credit_history              purpose  \
1        0<=X<200        48  'existing paid'             radio/tv   
3              <0        42  'existing paid'  furniture/equipment   

   credit_amount savings_status employment  installment_commitment  \
1           5951           <100     1<=X<4                       2   
3           7882           <100     4<=X<7                       2   

        personal_status other_parties  ...  property_magnitude age  \
1  'female div/dep/mar'          none  ...       'real estate'  22   
3         'male single'     guarantor  ...    'life insurance'  45   

   other_payment_plans     housing existing_credits      job num_dependents  \
1                 none         own                1  skilled              1   
3                 none  'for free'                1  skilled              2   

   own_telephone foreign_worker class  
1           none            yes   bad  
3           none            yes  good  

[2 rows x 21 columns]

In [12]:
#filtro
dados.loc[dados['purpose'] == 'radio/tv']

checking_status  duration                    credit_history   purpose  \
0                <0         6  'critical/other existing credit'  radio/tv   
1          0<=X<200        48                   'existing paid'  radio/tv   
8     'no checking'        12                   'existing paid'  radio/tv   
12         0<=X<200        12                   'existing paid'  radio/tv   
15               <0        24                   'existing paid'  radio/tv   
..              ...       ...                               ...       ...   
989        0<=X<200        24  'critical/other existing credit'  radio/tv   
991   'no checking'        15                        'all paid'  radio/tv   
992              <0        18                   'existing paid'  radio/tv   
997   'no checking'        12                   'existing paid'  radio/tv   
998              <0        45                   'existing paid'  radio/tv   

     credit_amount      savings_status employment  installment_commitment  \
0             1169  'no known savings'        >=7                       4   
1             5951                <100     1<=X<4                       2   
8             3059              >=1000     4<=X<7                       2   
12            1567                <100     1<=X<4                       1   
15            1282          100<=X<500     1<=X<4                       4   
..             ...                 ...        ...                     ...   
989           1743                <100        >=7                       4   
991           1569          100<=X<500        >=7                       4   
992           1936  'no known savings'     4<=X<7                       2   
997            804                <100        >=7                       4   
998           1845                <100     1<=X<4                       4   

          personal_status other_parties  ...   property_magnitude age  \
0           'male single'          none  ...        'real estate'  67   
1    'female div/dep/mar'          none  ...        'real estate'  22   
8          'male div/sep'          none  ...        'real estate'  61   
12   'female div/dep/mar'          none  ...                  car  22   
15   'female div/dep/mar'          none  ...                  car  32   
..                    ...           ...  ...                  ...  ..   
989         'male single'          none  ...     'life insurance'  48   
991         'male single'          none  ...                  car  34   
992        'male mar/wid'          none  ...                  car  23   
997         'male single'          none  ...                  car  38   
998         'male single'          none  ...  'no known property'  23   

     other_payment_plans     housing existing_credits                   job  \
0                   none         own                2               skilled   
1                   none         own                1               skilled   
8                   none         own                1  'unskilled resident'   
12                  none         own                1               skilled   
15                  none         own                1  'unskilled resident'   
..                   ...         ...              ...                   ...   
989                 none         own                2  'unskilled resident'   
991                 bank         own                1  'unskilled resident'   
992                 none        rent                2  'unskilled resident'   
997                 none         own                1               skilled   
998                 none  'for free'                1               skilled   

    num_dependents  own_telephone foreign_worker class  
0                1            yes            yes  good  
1                1           none            yes   bad  
8                1           none            yes  good  
12               1            yes            yes  good  
15               1           none          

In [13]:
#outra condição
dados.loc[dados['credit_amount'] > 18000]

checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]

In [14]:
#atribuimos resultado a variavel, criando outro df
credito2 = dados.loc[dados['credit_amount'] > 18000]
print(credito2)

    checking_status  duration         credit_history purpose  credit_amount  \
915        0<=X<200        48  'no credits/all paid'   other          18424   

    savings_status employment  installment_commitment       personal_status  \
915           <100     1<=X<4                       1  'female div/dep/mar'   

    other_parties  ...  property_magnitude age  other_payment_plans housing  \
915          none  ...    'life insurance'  32                 bank     own   

    existing_credits                          job num_dependents  \
915                1  'high qualif/self emp/mgmt'              1   

     own_telephone foreign_worker class  
915            yes             no   bad  

[1 rows x 21 columns]


In [15]:
#definimos só algumas colunas
credito3 = dados[['checking_status','duration']].loc[dados['credit_amount'] > 18000]
print(credito3)

    checking_status  duration
915        0<=X<200        48


In [16]:
#séries, única coluna
# pode ser criada a partr de listas, array do numpy ou coluna do data frame
s1 = pd.Series([2,5,3,34,54,23,1,16])
print(s1)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


In [17]:
#series a partir de um dataframe
s3 = dados['purpose']
print(s3)
type(s3)

0                 radio/tv
1                 radio/tv
2                education
3      furniture/equipment
4                'new car'
              ...         
995    furniture/equipment
996             'used car'
997               radio/tv
998               radio/tv
999             'used car'
Name: purpose, Length: 1000, dtype: object


pandas.core.series.Series

In [19]:
#note a diferenca, temos um daa frame
d4 = dados[['purpose']]
type(d4)

pandas.core.frame.DataFrame

In [20]:
#renomear
dados.rename(columns={"duration":"duração","purpose":"propósito"})

checking_status  duração                    credit_history  \
0                <0        6  'critical/other existing credit'   
1          0<=X<200       48                   'existing paid'   
2     'no checking'       12  'critical/other existing credit'   
3                <0       42                   'existing paid'   
4                <0       24              'delayed previously'   
..              ...      ...                               ...   
995   'no checking'       12                   'existing paid'   
996              <0       30                   'existing paid'   
997   'no checking'       12                   'existing paid'   
998              <0       45                   'existing paid'   
999        0<=X<200       45  'critical/other existing credit'   

               propósito  credit_amount      savings_status  employment  \
0               radio/tv           1169  'no known savings'         >=7   
1               radio/tv           5951                <100      1<=X<4   
2              education           2096                <100      4<=X<7   
3    furniture/equipment           7882                <100      4<=X<7   
4              'new car'           4870                <100      1<=X<4   
..                   ...            ...                 ...         ...   
995  furniture/equipment           1736                <100      4<=X<7   
996           'used car'           3857                <100      1<=X<4   
997             radio/tv            804                <100         >=7   
998             radio/tv           1845                <100      1<=X<4   
999           'used car'           4576          100<=X<500  unemployed   

     installment_commitment       personal_status other_parties  ...  \
0                         4         'male single'          none  ...   
1                         2  'female div/dep/mar'          none  ...   
2                         2         'male single'          none  ...   
3                         2         'male single'     guarantor  ...   
4                         3         'male single'          none  ...   
..                      ...                   ...           ...  ...   
995                       3  'female div/dep/mar'          none  ...   
996                       4        'male div/sep'          none  ...   
997                       4         'male single'          none  ...   
998                       4         'male single'          none  ...   
999                       3         'male single'          none  ...   

      property_magnitude age  other_payment_plans     housing  \
0          'real estate'  67                 none         own   
1          'real estate'  22                 none         own   
2          'real estate'  49                 none         own   
3       'life insurance'  45                 none  'for free'   
4    'no known property'  53                 none  'for free'   
..                   ...  ..                  ...         ...   
995        'real estate'  31                 none         own   
996     'life insurance'  40                 none         own   
997                  car  38                 none         own   
998  'no known property'  23                 none  'for free'   
999                  car  27                 none         own   

    existing_credits                          job num_dependents  \
0                  2                      skilled              1   
1                  1                      skilled              1   
2                  1         'unskilled resident'              2   
3                  1                      skilled              2   
4                  2                      skilled              2   
..               ...                          ...            ...   
995                1         'unskilled resident'              1   
996                1  'high qualif/self emp/mgmt'              1   
997                1                      skilled   

In [21]:
#porém a alteração não persiste
dados.head(1)

checking_status  duration                    credit_history   purpose  \
0              <0         6  'critical/other existing credit'  radio/tv   

   credit_amount      savings_status employment  installment_commitment  \
0           1169  'no known savings'        >=7                       4   

  personal_status other_parties  ...  property_magnitude age  \
0   'male single'          none  ...       'real estate'  67   

   other_payment_plans housing existing_credits      job num_dependents  \
0                 none     own                2  skilled              1   

   own_telephone foreign_worker class  
0            yes            yes  good  

[1 rows x 21 columns]

In [22]:
#excluir coluna
dados.drop('checking_status', axis=1, inplace=True)
print(dados)

     duration                    credit_history              purpose  \
0           6  'critical/other existing credit'             radio/tv   
1          48                   'existing paid'             radio/tv   
2          12  'critical/other existing credit'            education   
3          42                   'existing paid'  furniture/equipment   
4          24              'delayed previously'            'new car'   
..        ...                               ...                  ...   
995        12                   'existing paid'  furniture/equipment   
996        30                   'existing paid'           'used car'   
997        12                   'existing paid'             radio/tv   
998        45                   'existing paid'             radio/tv   
999        45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7       

In [23]:
#verificar dados nulos
dados.isnull()

duration  credit_history  purpose  credit_amount  savings_status  \
0       False           False    False          False           False   
1       False           False    False          False           False   
2       False           False    False          False           False   
3       False           False    False          False           False   
4       False           False    False          False           False   
..        ...             ...      ...            ...             ...   
995     False           False    False          False           False   
996     False           False    False          False           False   
997     False           False    False          False           False   
998     False           False    False          False           False   
999     False           False    False          False           False   

     employment  installment_commitment  personal_status  other_parties  \
0         False                   False            False          False   
1         False                   False            False          False   
2         False                   False            False          False   
3         False                   False            False          False   
4         False                   False            False          False   
..          ...                     ...              ...            ...   
995       False                   False            False          False   
996       False                   False            False          False   
997       False                   False            False          False   
998       False                   False            False          False   
999       False                   False            False          False   

     residence_since  property_magnitude    age  other_payment_plans  housing  \
0              False               False  False                False    False   
1              False               False  False                False    False   
2              False               False  False                False    False   
3              False               False  False                False    False   
4              False               False  False                False    False   
..               ...                 ...    ...                  ...      ...   
995            False               False  False                False    False   
996            False               False  False                False    False   
997            False               False  False                False    False   
998            False               False  False                False    False   
999            False               False  False                False    False   

     existing_credits    job  num_dependents  own_telephone  foreign_worker  \
0               False  False           False          False           False   
1               False  False           False          False           False   
2               False  False           False          False           False   
3               False  False           False          False           False   
4               False  False           False          False           False   
..                ...    ...             ...            ...             ...   
995             False  False           False          False           False   
996             False  False           False          False           False   
997             False  False           False          False           False   
998             False  False           False          False           False   
999             False  False           False          False           False   

     class  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
995  False  
996  False  
997  False  
998  False  
999  False  

[1000 rows x 20 columns]

In [24]:
#verificar qtd de dados nulos
dados.isnull().sum()

duration                  0
credit_history            0
purpose                   0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [25]:
#retirar colunas com NaN
dados.dropna()

duration                    credit_history              purpose  \
0           6  'critical/other existing credit'             radio/tv   
1          48                   'existing paid'             radio/tv   
2          12  'critical/other existing credit'            education   
3          42                   'existing paid'  furniture/equipment   
4          24              'delayed previously'            'new car'   
..        ...                               ...                  ...   
995        12                   'existing paid'  furniture/equipment   
996        30                   'existing paid'           'used car'   
997        12                   'existing paid'             radio/tv   
998        45                   'existing paid'             radio/tv   
999        45  'critical/other existing credit'           'used car'   

     credit_amount      savings_status  employment  installment_commitment  \
0             1169  'no known savings'         >=7                       4   
1             5951                <100      1<=X<4                       2   
2             2096                <100      4<=X<7                       2   
3             7882                <100      4<=X<7                       2   
4             4870                <100      1<=X<4                       3   
..             ...                 ...         ...                     ...   
995           1736                <100      4<=X<7                       3   
996           3857                <100      1<=X<4                       4   
997            804                <100         >=7                       4   
998           1845                <100      1<=X<4                       4   
999           4576          100<=X<500  unemployed                       3   

          personal_status other_parties  residence_since   property_magnitude  \
0           'male single'          none                4        'real estate'   
1    'female div/dep/mar'          none                2        'real estate'   
2           'male single'          none                3        'real estate'   
3           'male single'     guarantor                4     'life insurance'   
4           'male single'          none                4  'no known property'   
..                    ...           ...              ...                  ...   
995  'female div/dep/mar'          none                4        'real estate'   
996        'male div/sep'          none                4     'life insurance'   
997         'male single'          none                4                  car   
998         'male single'          none                4  'no known property'   
999         'male single'          none                4                  car   

     age other_payment_plans     housing  existing_credits  \
0     67                none         own                 2   
1     22                none         own                 1   
2     49                none         own                 1   
3     45                none  'for free'                 1   
4     53                none  'for free'                 2   
..   ...                 ...         ...               ...   
995   31                none         own                 1   
996   40                none         own                 1   
997   38                none         own                 1   
998   23                none  'for free'                 1   
999   27                none         own                 1   

                             job  num_dependents own_telephone foreign_worker  \
0                        skilled               1           yes            yes   
1                        skilled               1          none            yes   
2           'unskilled resident'               2          none            yes   
3                        skilled               2          none            yes   
4                        skilled               2          none            yes   

In [27]:
#preencher dados faltantes
dados["duration"].fillna(0, inplace=True)

In [28]:
#iloc
dados.iloc[0:3,0:5]

duration                    credit_history    purpose  credit_amount  \
0         6  'critical/other existing credit'   radio/tv           1169   
1        48                   'existing paid'   radio/tv           5951   
2        12  'critical/other existing credit'  education           2096   

       savings_status  
0  'no known savings'  
1                <100  
2                <100

In [29]:
dados.iloc[[0,1,2,3,7],0:5]

duration                    credit_history              purpose  \
0         6  'critical/other existing credit'             radio/tv   
1        48                   'existing paid'             radio/tv   
2        12  'critical/other existing credit'            education   
3        42                   'existing paid'  furniture/equipment   
7        36                   'existing paid'           'used car'   

   credit_amount      savings_status  
0           1169  'no known savings'  
1           5951                <100  
2           2096                <100  
3           7882                <100  
7           6948                <100

##modulos e pacotes

In [30]:
import statistics as s
z = [10,20,30,40]
x = s.mean(z)
y = s.median(z)
print(x)
print(y)


25
25.0


#Exercicios


In [32]:
# Faça um programa que tenha uma função chamada amplitude. A função deve receber uma lista e imprimir a amplitude.
# Crie também um código para testar sua função

def amplitude(lista):
  maior = max(lista)
  menor = min(lista)
  print(maior-menor)

lista = [3,20,2,65,7,9,10]
amplitude(lista)

63


In [ ]:
# Faça uma função que receba uma string e imprima esta string na forma vertical Por exemplo, se receber python, deve imprimir
# p
# y
# t
# h
# o
# n
# Dica: uma string do python funciona como uma lista! Crie também um código para testar sua função

In [34]:
def imprimeVertical(palavra: str):
  for n in range(0, len(palavra)):
    print(palavra[n])

word = "Lucas"
imprimeVertical(word)

L
u
c
a
s


In [42]:
# Crie um programa que leia o peso de uma carga em números inteiros. Se o peso for até 10 kg, informe que o valor será de R$ 50,00.
# Entre 11 e 20 kg, informe que o valor será de R$ 80.
# Se for maior que 20 informe que o transporte não é aceito. Teste vários pesos.
peso = input("Informe um peso (em Kg):")
peso = float(peso)
if(peso <= 10):
  print("Valor: R$ 50,00")
elif (peso >10 and peso <=20):
  print("Valor: R$ 80,00")
else:
  print("Tansporte não aceita esta carga!")

Informe um peso (em Kg):2
Valor: R$ 50,00
